# Atelier NumPy : Introduction et Applications Pratiques

## Introduction à NumPy

### Présentation de NumPy
#### Qu'est-ce que NumPy ?
- NumPy est une bibliothèque pour le langage Python, utilisée pour les calculs scientifiques.
- Elle permet de manipuler des tableaux de grandes dimensions de manière efficace.

#### Pourquoi utiliser NumPy ?
- NumPy est beaucoup plus rapide que les listes Python pour les opérations sur des grandes quantités de données.
- Il fournit une grande variété de fonctions pour des opérations mathématiques, logiques, de manipulation de formes, de tri, de sélection, d'entrées/sorties, et bien plus.

#### Installation de NumPy
```bash
pip install numpy
```

### Importation de NumPy
```Python
import numpy as np
```

### Création de Tableaux NumPy

#### À partir de listes Python
``` Python
a = np.array([1, 2, 3, 4, 5])
print("Tableau 1D:", a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print("Tableau 2D:\n", b)
```


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [4]:
b = np.array([
    [1,2,3],
    [4,5,6]
])

In [5]:
b.shape

(2, 3)

### Utilisation de fonctions NumPy
#### Création d'un tableau de zéros
```Python
zeros = np.zeros((3, 4))
print("Tableau de zéros:\n", zeros)
```

In [6]:
# Initialisation d'une tableau de zeros
zeros = np.zeros((3,4))

In [7]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Création d'un tableau de uns
```Python
ones = np.ones((2, 3))
print("Tableau de uns:\n", ones)
```

In [8]:
ones = np.ones((2,3))

In [9]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
ones.shape

(2, 3)

### Création d'un tableau avec une séquence d'entiers
```Python
arange = np.arange(10, 20)
print("Tableau avec arange:\n", arange)
```

In [12]:
arange = np.arange(10, 20)

In [13]:
arange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Création d'un tableau avec des valeurs réparties uniformément
```Python
linspace = np.linspace(0, 1, 5)
print("Tableau avec linspace:\n", linspace)
```

In [14]:
linspace = np.linspace(0, 1, 5)

In [15]:
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Indexation et Slicing

#### Accès aux éléments

```Python
print("Élément à l'indice 2 de a:", a[2])
print("Élément à la position (1, 2) de b:", b[1, 2])
```



In [17]:
a[2:4]

array([3, 4])

#### Slicing
```Python
print("Slicing de a (du 2e au 4e élément):", a[1:4])
print("Slicing de b (toutes les lignes, 2e colonne):", b[:, 1])
```


### Modification des Tableaux

#### Modification d'éléments

```Python
a[2] = 10
print("a après modification:", a)

b[0, 1] = 7
print("b après modification:\n", b)
```


#### Reshape et resize
```Python
c = np.arange(8)
print("Tableau original:\n", c)
c_reshaped = c.reshape((2, 4))
print("Tableau après reshape:\n", c_reshaped)
```


In [18]:
c = np.arange(8)

In [19]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
c.shape

(8,)

In [21]:
c_reshape = c.reshape((2,4))

In [22]:
c_reshape

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Ajout et suppression d'éléments

```Python
c_appended = np.append(c, [10, 11])
print("Tableau après ajout d'éléments:\n", c_appended)

c_deleted = np.delete(c, [1, 3])
print("Tableau après suppression d'éléments:\n", c_deleted)
```



### Opérations sur les Tableaux NumPy

#### Opérations Mathématiques

```Python
d = np.array([1, 2, 3, 4])
e = np.array([5, 6, 7, 8])

print("Addition de d et e:", d + e)
print("Multiplication de d et e:", d * e)
```

In [23]:
d = np.array([1, 2, 3, 4])
e = np.array([5, 6, 7, 8])

In [24]:
f = d + e
f

array([ 6,  8, 10, 12])

In [26]:
multiplication = 2 * d * e

multiplication

array([10, 24, 42, 64])

In [27]:
secondTableau = np.array([2])

In [28]:
mul = d * secondTableau
mul

array([2, 4, 6, 8])

### Fonctions universelles (ufuncs)
```Python
print("Racine carrée de d:", np.sqrt(d))
print("Exponentielle de d:", np.exp(d))

```

In [29]:
exp = np.sqrt(d)
exp

array([1.        , 1.41421356, 1.73205081, 2.        ])

### Statistiques de Base

```Python
print("Moyenne de d:", np.mean(d))
print("Médiane de d:", np.median(d))
print("Écart-type de d:", np.std(d))
```

### Opérations Logiques
```Python
print("d égal à e:", np.equal(d, e))
print("d plus grand que 2:", np.greater(d, 2))

print("Opération logique AND:", np.logical_and(d > 2, e > 6))
print("Opération logique OR:", np.logical_or(d > 2, e > 6))
```

### Simulation de Données
#### Génération de données aléatoires

```Python
random_data = np.random.rand(5, 5)
print("Données aléatoires:\n", random_data)

# Simulations simples
# Simulation de lancer de dés
dice_rolls = np.random.randint(1, 7, size=10)
print("Lancer de dés:\n", dice_rolls)
```

In [30]:
random_data = np.random.rand(5, 5)
random_data

array([[0.53591359, 0.37105164, 0.74896271, 0.10879086, 0.3312349 ],
       [0.76817386, 0.98272318, 0.7725832 , 0.53620427, 0.06998915],
       [0.1337974 , 0.61041002, 0.06418361, 0.63037428, 0.08676137],
       [0.57687387, 0.90498332, 0.14068897, 0.20255582, 0.23947887],
       [0.53555421, 0.23994066, 0.56376904, 0.68723399, 0.66215637]])

### Exercice NumPy : Analyse des Données de Vente

#### Contexte
Vous travaillez pour une entreprise qui vend des produits en ligne. Vous avez des données de vente mensuelles pour une période de six mois. Les données comprennent le nombre de produits vendus et les revenus générés chaque mois. Vous allez utiliser NumPy pour analyser ces données et extraire des informations utiles.

#### Données de Vente
Les données sont sous forme de tableaux NumPy :
- `produits_vendus` : Un tableau 1D contenant le nombre de produits vendus chaque mois.
- `revenus` : Un tableau 1D contenant les revenus générés chaque mois.

Voici les données pour les six mois :
- Produits vendus : `[150, 200, 180, 220, 210, 190]`
- Revenus en milliers de dollars : `[75, 100, 90, 110, 105, 95]`

#### Objectifs
1. Créer et afficher les tableaux `produits_vendus` et `revenus`.
2. Calculer et afficher le total des produits vendus et des revenus pour les six mois.
3. Calculer et afficher le nombre moyen de produits vendus par mois et le revenu moyen par mois.
4. Identifier le mois avec le plus grand nombre de produits vendus et celui avec le revenu le plus élevé.
5. Visualiser les données de vente sous forme de graphique.

### Instructions

#### Étape 1 : Créer et Afficher les Tableaux
Créez les tableaux `produits_vendus` et `revenus` à partir des données fournies et affichez-les.

#### Étape 2 : Calculer le Total des Produits Vendus et des Revenus
Utilisez les fonctions NumPy pour calculer le total des produits vendus et des revenus pour les six mois.

#### Étape 3 : Calculer les Moyennes Mensuelles
Calculez le nombre moyen de produits vendus par mois et le revenu moyen par mois.

#### Étape 4 : Identifier les Mois avec les Ventes et les Revenus les Plus Élevés
Utilisez les fonctions NumPy pour identifier le mois avec le plus grand nombre de produits vendus et celui avec le revenu le plus élevé.

#### Étape 5 : Visualiser les Données
Utilisez Matplotlib pour créer un graphique montrant les produits vendus et les revenus pour chaque mois.


### Exercice NumPy : Analyse des Données Météorologiques

#### Contexte
Vous travaillez pour un service météorologique et vous devez analyser les données de température quotidienne enregistrées sur une période de 30 jours dans une ville. Vous utiliserez NumPy pour analyser ces données et extraire des informations utiles.

#### Données Météorologiques
Les données de température (en degrés Celsius) pour les 30 jours sont les suivantes :
```
[22.1, 23.3, 21.7, 22.5, 24.0, 25.1, 23.8, 24.5, 23.0, 22.9, 21.4, 20.8, 22.3, 24.1, 25.6,
 24.3, 23.7, 22.8, 21.9, 22.4, 23.2, 22.7, 21.6, 20.9, 21.5, 22.6, 23.9, 24.2, 25.0, 24.7]
```

#### Objectifs
1. Créer et afficher le tableau des températures.
2. Calculer et afficher la température moyenne sur les 30 jours.
3. Trouver et afficher les jours avec la température maximale et minimale.
4. Calculer et afficher la variance et l'écart-type des températures.
5. Créer un graphique de la température quotidienne.

### Instructions

#### Étape 1 : Créer et Afficher le Tableau des Températures
Créez le tableau `temperatures` à partir des données fournies et affichez-le.

#### Étape 2 : Calculer la Température Moyenne
Utilisez NumPy pour calculer la température moyenne sur les 30 jours.

#### Étape 3 : Trouver les Jours avec les Températures Maximale et Minimale
Utilisez NumPy pour trouver les jours avec les températures maximale et minimale.

#### Étape 4 : Calculer la Variance et l'Écart-type
Utilisez NumPy pour calculer la variance et l'écart-type des températures.

#### Étape 5 : Créer un Graphique de la Température Quotidienne
Utilisez Matplotlib pour créer un graphique de la température quotidienne.